name: CI

on:
  schedule:
    - cron: "* */4 * * *" # every 4 hours
  push:
    branches:
      - master

jobs:
  job-sync-project-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Sync Data
        uses: ./.github/actions/sync-data
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-stats: "true"

      - name: Commit data files
        run: |
          git config --local user.email "opensource+website@newrelic.com"
          git config --local user.name "Actionbot"
          echo "Updated project data files -- committing"
          git commit src/data -m "chore: updated project data files"

      - name: Push Commit
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  job-deploy-staging:
    runs-on: ubuntu-latest
    needs: job-sync-project-data
    env:
      STAGING_WEBHOOK: ${{ secrets.AMPLIFY_STAGING_WEBHOOK }}
    steps:
      - name: Call Amplify Staging Deploy
        run: |
          echo "Calling Amplify staging webhook"
          curl --silent --show-error --output /dev/null -X POST $STAGING_WEBHOOK -H "Content-Type:application/json"
          echo "**OUTPUT SUPPRESSED**"
          echo "Webhook call complete"

  job-deploy-prod:
    runs-on: ubuntu-latest
    needs: job-sync-project-data
    env:
      PROD_WEBHOOK: ${{ secrets.AMPLIFY_PROD_WEBHOOK }}
    steps:
      - name: Call Amplify Prod Deploy
        run: |
          echo "Calling Amplify prod webhook"
          curl --silent --show-error --output /dev/null -X POST $PROD_WEBHOOK -H "Content-Type:application/json"
          echo "**OUTPUT SUPPRESSED**"
          echo "Webhook call complete"
