name: CI

on:
  schedule:
    - cron: "* */4 * * *" # every 4 hours
  push:
    branches:
      - master

jobs:
  job-sync-project-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Sync Data
        uses: ./.github/actions/sync-data
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-stats: "true"

      - name: Commit data files
        run: |
          git config --local user.email "opensource+nr1-catalog@newrelic.com"
          git config --local user.name "Actionbot"
          echo "Updated project data files -- committing"
          git commit src/data -m "chore: updated project data files"

      - name: Push Commit
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  # Merge/Commit to master branch
  job-deploy-prod:
    if: github.event_name != 'schedule'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install Dependencies
        run: npm ci
      # - name: Gatsby Build
      #   run: npm run build

      # alternatively, download the amplify-cli and run commands without this action
      - name: Amplify - Configure
        uses: ambientlight/amplify-cli-action@0.2.1
        with:
          amplify_command: configure
          amplify_env: prod
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Amplify - Deploy
        uses: ambientlight/amplify-cli-action@0.2.1
        with:
          amplify_command: publish
          amplify_env: prod
          # build_command: 'npm run build' # Is this needed?
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
